version: '3.8'

services:
  react-showroom:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: react_showroom_app
    ports:
      - "5173:5173" # Mapea el puerto local al contenedor
    volumes:
      - .:/app # Sincroniza tu código local con el contenedor (Hot Reload)
      - /app/node_modules # Evita sobreescribir los node_modules del contenedor
    environment:
      - CHOKIDAR_USEPOLLING=true # Asegura que React detecte los cambios en Linux/Windows/Mac